//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataTemp
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string SoPhieuThu { get; set; }
        public string NguoiLapPhieu { get; set; }
        public string HocVien { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public string Quan { get; set; }
        public string ThanhPho { get; set; }
        public Nullable<System.DateTime> SinhNhat { get; set; }
        public string MoTa { get; set; }
        public string NgheNghiep { get; set; }
        public string MucDichHoc { get; set; }
        public string DauVao { get; set; }
        public string DauRa { get; set; }
        public string KhoaHoc { get; set; }
        public string CapToc { get; set; }
        public string NgayThi { get; set; }
    }
}
