//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TargetBonus
    {
        public int ID { get; set; }
        public Nullable<int> CampaignID { get; set; }
        public Nullable<int> TargetType { get; set; }
        public Nullable<double> TargetFinishPercent { get; set; }
        public string ImageLink { get; set; }
        public string DescriptionBonus { get; set; }
        public Nullable<bool> IsHide { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<double> TargetRevenue { get; set; }
    }
}
