//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccountTotalHourTeaching
    {
        public int ID { get; set; }
        public Nullable<int> Type { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<int> HoursOnline { get; set; }
        public Nullable<int> RealHour { get; set; }
        public Nullable<int> RealHourOnline { get; set; }
        public Nullable<int> AbsentHour { get; set; }
        public Nullable<int> AbsentHourOnline { get; set; }
        public Nullable<int> TotalHour { get; set; }
        public Nullable<int> TotalHourOnline { get; set; }
        public Nullable<int> HoursCourseSelfStudy { get; set; }
        public Nullable<int> HoursCourseSelfStudyOnline { get; set; }
        public Nullable<int> TotalHourCourseSelfStudy { get; set; }
        public Nullable<int> TotalHourCourseSelfStudyOnline { get; set; }
        public Nullable<System.DateTime> DateRun { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> LeaderHoursOffline { get; set; }
        public Nullable<int> LeaderHoursOnline { get; set; }
        public Nullable<int> LeaderRealHour { get; set; }
        public Nullable<int> LeaderRealHourOnline { get; set; }
        public Nullable<int> LeaderAbsentHour { get; set; }
        public Nullable<int> LeaderAbsentHourOnline { get; set; }
        public Nullable<int> LeaderTotalHour { get; set; }
        public Nullable<int> LeaderTotalHourOnline { get; set; }
        public Nullable<int> LeaderHoursCourseSelfStudy { get; set; }
        public Nullable<int> LeaderHoursCourseSelfStudyOnline { get; set; }
        public Nullable<int> LeaderTotalHourCourseSelfStudy { get; set; }
        public Nullable<int> LeaderTotalHourCourseSelfStudyOnline { get; set; }
    }
}
