//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Class
    {
        public int ID { get; set; }
        public Nullable<int> GradeID { get; set; }
        public string GradeName { get; set; }
        public string ClassName { get; set; }
        public Nullable<bool> isHide { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> PriceClass { get; set; }
        public Nullable<int> PriceClassInitial { get; set; }
        public Nullable<int> TypeClass { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> Language { get; set; }
        public Nullable<int> Coefficient { get; set; }
        public string CoefficientName { get; set; }
    }
}
