//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ServicesStudent
    {
        public int ID { get; set; }
        public Nullable<int> StudentUID { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> PriceService { get; set; }
        public string Note { get; set; }
        public Nullable<int> PaymentmethodID { get; set; }
        public string PaymentmethodName { get; set; }
        public Nullable<bool> isHide { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> ServiceExamsID { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public Nullable<double> Listening { get; set; }
        public Nullable<double> Speaking { get; set; }
        public Nullable<double> Reading { get; set; }
        public Nullable<double> Writing { get; set; }
        public Nullable<double> TaskOne { get; set; }
        public Nullable<double> TaskTwo { get; set; }
        public Nullable<double> OverAll { get; set; }
        public Nullable<int> SupplierServicesID { get; set; }
        public string SupplierServices { get; set; }
        public Nullable<System.DateTime> DateService { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public string CertificateFile { get; set; }
    }
}
