//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PostContent
    {
        public int ID { get; set; }
        public string TitlePost { get; set; }
        public string PostIMG { get; set; }
        public string ContentPost { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> NumberView { get; set; }
        public Nullable<bool> isHideStaff { get; set; }
        public Nullable<bool> isHideStudent { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> StatusPost { get; set; }
        public Nullable<bool> BackgroundPost { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string PostIMGThumbnail { get; set; }
        public Nullable<int> PostType { get; set; }
    }
}
