//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SupplierServices
    {
        public int ID { get; set; }
        public string SupplierName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> isHide { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string Address { get; set; }
        public string MST { get; set; }
        public string Represent { get; set; }
        public string Phone { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string StatusName { get; set; }
        public string CuratorFullName { get; set; }
    }
}
