//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SetPackageHistory
    {
        public int ID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> SetpackageID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsHide { get; set; }
        public string GroupResult { get; set; }
        public string GroupQuestion { get; set; }
        public Nullable<int> SetpackageDetailID { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public Nullable<int> TotalCorrect { get; set; }
        public Nullable<double> TotalPoint { get; set; }
        public Nullable<int> Times { get; set; }
    }
}
