//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Target
    {
        public int ID { get; set; }
        public Nullable<int> CampaignID { get; set; }
        public Nullable<int> MainTargetID { get; set; }
        public Nullable<int> TargetType { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<double> TargetValue { get; set; }
        public Nullable<double> CurrentValue { get; set; }
        public string Note { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public Nullable<bool> IsHide { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
