//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SetPackageDetail
    {
        public int ID { get; set; }
        public Nullable<int> SetPackageID { get; set; }
        public Nullable<int> TypeDetail { get; set; }
        public string PackageDetailName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Minute { get; set; }
        public string LinkAudio { get; set; }
        public Nullable<bool> isHide { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
