//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ZoomMeetingInternal
    {
        public int ID { get; set; }
        public string Topic { get; set; }
        public Nullable<int> RangeType { get; set; }
        public string RangeTypeName { get; set; }
        public string ArrayUID { get; set; }
        public Nullable<bool> isStart { get; set; }
        public Nullable<bool> isSendMail { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string StartTime { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string RoomId { get; set; }
        public string RoomPass { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
