//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Courses
    {
        public int ID { get; set; }
        public Nullable<int> GradeID { get; set; }
        public string GradeName { get; set; }
        public Nullable<int> ClassID { get; set; }
        public string ClassName { get; set; }
        public string CourseName { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public Nullable<System.DateTime> EndingDate { get; set; }
        public Nullable<int> StudyTimeID { get; set; }
        public string StudyTimeName { get; set; }
        public Nullable<int> TietHoc { get; set; }
        public Nullable<int> CurriculumsID { get; set; }
        public string CurriculumsName { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string SchoolName { get; set; }
        public Nullable<int> Status { get; set; }
        public string StatusName { get; set; }
        public Nullable<int> SchoolRoomID { get; set; }
        public string SchoolRoomName { get; set; }
        public Nullable<bool> CourseSelfStudy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> CountStudent { get; set; }
        public Nullable<int> AcademicUID { get; set; }
        public string AcademicName { get; set; }
        public Nullable<int> TeacherLeaderUID { get; set; }
        public string TeacherLeaderName { get; set; }
        public Nullable<int> TypeCourse { get; set; }
        public string TypeCourseName { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<bool> Mail3Lesson { get; set; }
        public Nullable<int> DifferenceSchedule { get; set; }
        public Nullable<int> Lesson { get; set; }
    }
}
