//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TempPayroll
    {
        public int ID { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<int> CampaignID { get; set; }
        public string FullName { get; set; }
        public Nullable<double> BasicSalary { get; set; }
        public Nullable<double> Revenue { get; set; }
        public Nullable<double> RevenuePercent { get; set; }
        public Nullable<double> BonusSalary { get; set; }
        public Nullable<double> DeductedSalary { get; set; }
        public Nullable<int> CareQuantity { get; set; }
        public Nullable<double> CarePrice { get; set; }
        public Nullable<int> CarePlusQuantity { get; set; }
        public Nullable<double> CarePlusPrice { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
