//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ServiceExams
    {
        public int ID { get; set; }
        public string ExamService { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public Nullable<bool> isHide { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> Slot { get; set; }
        public Nullable<int> ExamPrice { get; set; }
        public Nullable<int> OriginalPrice { get; set; }
        public Nullable<bool> ExamReal { get; set; }
        public string Hour { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> DiscountID { get; set; }
    }
}
