//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalaryPaidHistory
    {
        public int ID { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<int> CampaignID { get; set; }
        public string SalaryMonth { get; set; }
        public Nullable<int> SalarySaler { get; set; }
        public Nullable<int> CountSourceZim { get; set; }
        public Nullable<int> SalarySourceZim { get; set; }
        public Nullable<int> TotalSourceZim { get; set; }
        public Nullable<int> CountSourceUID { get; set; }
        public Nullable<int> SalarySettingID { get; set; }
        public Nullable<int> SalarySettingPercent { get; set; }
        public Nullable<int> TotalSourceUID { get; set; }
        public Nullable<int> SalaryLessonTeacher { get; set; }
        public Nullable<int> CountLesson { get; set; }
        public Nullable<int> TotalLesson { get; set; }
        public Nullable<int> SalaryWorkStaff { get; set; }
        public Nullable<int> WorkDay { get; set; }
        public Nullable<int> TotalWork { get; set; }
        public Nullable<int> AdditionFee { get; set; }
        public Nullable<double> PaidReal { get; set; }
        public string Note { get; set; }
        public Nullable<bool> isHide { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<double> PercentBonus { get; set; }
        public Nullable<double> TotalBonus { get; set; }
        public Nullable<double> PercentTip { get; set; }
        public Nullable<double> TotalTip { get; set; }
        public Nullable<double> TotalRevenue { get; set; }
    }
}
