//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Discount
    {
        public int ID { get; set; }
        public string DiscountCode { get; set; }
        public Nullable<int> DiscountPrice { get; set; }
        public Nullable<int> DiscountPercent { get; set; }
        public Nullable<bool> DiscountType { get; set; }
        public Nullable<int> Status { get; set; }
        public string StatusName { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> QuantityLeft { get; set; }
        public Nullable<bool> isHide { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
