//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Invoices
    {
        public int ID { get; set; }
        public Nullable<bool> Refund { get; set; }
        public Nullable<int> CourseStudentID { get; set; }
        public Nullable<int> AppointmentID { get; set; }
        public Nullable<int> ServiceStudent { get; set; }
        public Nullable<int> RefundID { get; set; }
        public Nullable<int> ComboID { get; set; }
        public Nullable<int> StudentUID { get; set; }
        public string StudentFullName { get; set; }
        public string StudentPhone { get; set; }
        public string StudentAddress { get; set; }
        public string ReasonNote { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> PriceLeft { get; set; }
        public string QRCode { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> DatePriceLeft { get; set; }
        public Nullable<int> RewardTeachers { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string IdentityCard { get; set; }
        public Nullable<System.DateTime> IdentityCardDate { get; set; }
        public string IdentityCardCity { get; set; }
        public string CreatedInvoice { get; set; }
        public string NumberInvoice { get; set; }
        public Nullable<int> PaymentmethodID { get; set; }
        public string PaymentmethodName { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string SchoolName { get; set; }
        public Nullable<int> NewComboID { get; set; }
        public Nullable<int> SetPackageStudentID { get; set; }
        public Nullable<bool> isHide { get; set; }
        public string Camket { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
