//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalaryTeacherOnline
    {
        public int ID { get; set; }
        public Nullable<int> TeacherUID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> PersentSalarySetting { get; set; }
        public Nullable<bool> PersentCourseType { get; set; }
        public string PersentCourseName { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
