//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ExerciseAddonStudentCheckFix
    {
        public int ID { get; set; }
        public int ExerciseAddonStudentID { get; set; }
        public Nullable<int> ExerciseAddonStudentID100END { get; set; }
        public int indexCount { get; set; }
        public string indexName { get; set; }
        public Nullable<int> StatusAcceptReject { get; set; }
        public Nullable<bool> isHide { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> UIDCheckFix { get; set; }
        public string UIDCheckFixName { get; set; }
    }
}
