//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CoursesSchedule
    {
        public int ID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<bool> CourseSelfStudy { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> CurriculumsDetailsID { get; set; }
        public Nullable<int> StudyTimeID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> SchoolRoomID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> TeacherAttendanceID { get; set; }
        public Nullable<bool> IsHide { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string RoomID { get; set; }
        public string RoomPass { get; set; }
        public Nullable<bool> isRoomStart { get; set; }
        public Nullable<int> FisnishStatus { get; set; }
        public Nullable<bool> IsSendMail { get; set; }
        public string ZoomStartURL { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<bool> Notify { get; set; }
    }
}
