//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CoursesStudentHistoryChange
    {
        public int ID { get; set; }
        public Nullable<int> CoursesStudentID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string SchoolName { get; set; }
        public Nullable<int> StudentUID { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> CourseNewID { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> PriceCourse { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<int> PriceDiscout { get; set; }
        public Nullable<int> AppointmentID { get; set; }
        public Nullable<int> Deposit { get; set; }
        public Nullable<int> Paid { get; set; }
        public Nullable<int> TotalPaid { get; set; }
        public Nullable<int> PriceLeft { get; set; }
        public string Note { get; set; }
        public Nullable<int> PaymentmethodID { get; set; }
        public string PaymentmethodName { get; set; }
        public Nullable<bool> isHide { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> CampaignSaleID { get; set; }
        public Nullable<bool> Contract { get; set; }
        public Nullable<int> SupportUID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public string SourceName { get; set; }
        public Nullable<System.DateTime> DatePriceLeft { get; set; }
        public string Commitment { get; set; }
        public Nullable<bool> CourseReserve { get; set; }
        public Nullable<int> FatherID { get; set; }
    }
}
