//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_School
    {
        public int ID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string CityName { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string DistrictName { get; set; }
        public string SchoolAddress { get; set; }
        public string SchoolName { get; set; }
        public string SchoolPhone { get; set; }
        public Nullable<bool> isHide { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string CodeColor { get; set; }
    }
}
