//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SendEmailGroup
    {
        public int ID { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> AclogId { get; set; }
        public Nullable<int> TargetId { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
