//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DesiredStudyTime
    {
        public int ID { get; set; }
        public Nullable<int> StudentAppointmentID { get; set; }
        public Nullable<int> DayOfWeekID { get; set; }
        public string DayOfWeekName { get; set; }
        public Nullable<int> StudyTimeID { get; set; }
        public string StudyTimeName { get; set; }
        public Nullable<bool> isHide { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
