//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StudentAppointmentTest
    {
        public int ID { get; set; }
        public Nullable<int> StudentUID { get; set; }
        public string Phone { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string SchoolName { get; set; }
        public Nullable<System.DateTime> DateTest { get; set; }
        public string TimeTest { get; set; }
        public Nullable<int> UIDCreateTest { get; set; }
        public string CreateTestName { get; set; }
        public string Note { get; set; }
        public Nullable<bool> TestDone { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsSendNotify { get; set; }
        public Nullable<bool> isSendMail { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> AcademicID { get; set; }
        public string Color { get; set; }
        public string NumberOfLesson { get; set; }
        public string TimeOfLesson { get; set; }
        public string LinkDocument { get; set; }
        public string NationTime { get; set; }
        public Nullable<bool> IsHide { get; set; }
        public Nullable<System.DateTime> NoticeAcademic { get; set; }
        public Nullable<System.DateTime> NoticeResult { get; set; }
        public Nullable<double> SalaryTeacher { get; set; }
        public Nullable<bool> Payrolled { get; set; }
    }
}
