//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Refunds
    {
        public int ID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string SchoolName { get; set; }
        public Nullable<int> CourseStudentID { get; set; }
        public Nullable<int> AppointmentID { get; set; }
        public Nullable<int> ServiceStudent { get; set; }
        public Nullable<int> StudentUID { get; set; }
        public string StudentFullName { get; set; }
        public string StudentPhone { get; set; }
        public string ReasonNote { get; set; }
        public Nullable<int> Price { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string StatusName { get; set; }
        public string SourceRefund { get; set; }
        public Nullable<bool> RefundDone { get; set; }
        public Nullable<bool> KickOut { get; set; }
    }
}
