//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ExerciseAddonDraft
    {
        public int ID { get; set; }
        public string DraftName { get; set; }
        public Nullable<int> ExerciseAddonStudentID { get; set; }
        public string ExerciseQuestion { get; set; }
        public string FileAudio { get; set; }
        public string ParagraphAnswerFix { get; set; }
        public string NoteFix { get; set; }
        public Nullable<double> Scores { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
