//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ExerciseAddonStudent
    {
        public int ID { get; set; }
        public Nullable<int> UIDStudent { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> ExeGroupID { get; set; }
        public Nullable<int> ExerciseID { get; set; }
        public string ExerciseQuestion { get; set; }
        public Nullable<int> Type { get; set; }
        public string FileAudio { get; set; }
        public string ParagraphAnswer { get; set; }
        public string ParagraphAnswerFix { get; set; }
        public Nullable<int> ExerciseMultipleChoiseID { get; set; }
        public Nullable<int> UIDFix { get; set; }
        public string UIDFixName { get; set; }
        public string NoteFix { get; set; }
        public Nullable<int> UndoFixNumber { get; set; }
        public Nullable<double> Scores { get; set; }
        public Nullable<int> StatusDone { get; set; }
        public Nullable<double> ExercisePrice { get; set; }
        public Nullable<int> PayStatus { get; set; }
        public Nullable<int> RateExercise { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> UIDCreatedByExercise { get; set; }
        public string FullNameCreatedByExercise { get; set; }
        public Nullable<System.DateTime> RateDate { get; set; }
        public Nullable<bool> RejectCheckFix { get; set; }
        public Nullable<System.DateTime> RejectCheckFixDate { get; set; }
        public Nullable<int> SetPackageID { get; set; }
        public string SetPackageName { get; set; }
    }
}
