//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StudentAppointment
    {
        public int ID { get; set; }
        public Nullable<int> CampaignSaleID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string CityName { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string DistrictName { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string SchoolName { get; set; }
        public Nullable<int> ClassID { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> StudyID { get; set; }
        public string StudyName { get; set; }
        public Nullable<int> StudentUID { get; set; }
        public string StudentPhone { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> Deposit { get; set; }
        public string Note { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public string PaymentMethodName { get; set; }
        public Nullable<int> PaymentTeacherReceiveID { get; set; }
        public string PaymentTeacherReceiveName { get; set; }
        public Nullable<int> MoneyReceiverId { get; set; }
        public Nullable<bool> isHide { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> CloseAppointment { get; set; }
        public Nullable<int> CourseStudentID { get; set; }
        public Nullable<bool> CourseStudentReserve { get; set; }
        public Nullable<System.DateTime> DeadLineReserve { get; set; }
        public Nullable<System.DateTime> DateAppointment { get; set; }
        public Nullable<int> ComboID { get; set; }
        public Nullable<int> ClassPrice { get; set; }
        public Nullable<int> CommitmentID { get; set; }
        public string CommitmentName { get; set; }
        public Nullable<int> CommitmentPrice { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<int> DiscountPrice { get; set; }
        public Nullable<bool> DoneSalary { get; set; }
        public Nullable<double> DepositPercent { get; set; }
        public Nullable<int> CoefficientID { get; set; }
        public string CoefficientName { get; set; }
        public string ListWantToDay { get; set; }
        public Nullable<int> RewardTeachers { get; set; }
        public Nullable<bool> isCreateContract { get; set; }
        public Nullable<int> CustomPrice { get; set; }
        public Nullable<int> Lesson { get; set; }
    }
}
