//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Exercise
    {
        public int ID { get; set; }
        public Nullable<int> ExerciseGroupID { get; set; }
        public string ExerciseTitle { get; set; }
        public string FileName { get; set; }
        public string LinkFile { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> ExerciseAddonPrice { get; set; }
        public Nullable<int> WordLimit { get; set; }
        public Nullable<bool> isHide { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> TopicID { get; set; }
        public Nullable<int> PartNumber { get; set; }
        public Nullable<int> ParentQuestionID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string DescribeAnswer { get; set; }
    }
}
