//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Combo
    {
        public int ID { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<int> PriceDiscount { get; set; }
        public Nullable<int> Paid { get; set; }
        public Nullable<int> PriceLeft { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> PriceLeftDate { get; set; }
    }
}
