//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccountRank
    {
        public int ID { get; set; }
        public Nullable<int> Type { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<System.DateTime> DateRun { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> Rate1 { get; set; }
        public Nullable<int> Rate2 { get; set; }
        public Nullable<int> Rate3 { get; set; }
        public Nullable<int> Rate4 { get; set; }
        public Nullable<int> Rate5 { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<int> RoleRank { get; set; }
        public Nullable<double> TimeHour { get; set; }
        public Nullable<double> TotalTimeHour { get; set; }
    }
}
